# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\tikakonsept1.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1112, 1018)
        MainWindow.setStyleSheet("background-color: rgb(13, 140, 140);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(20, 120, 331, 821))
        self.frame.setStyleSheet("background-color: rgb(2, 81, 89);")
        self.frame.setObjectName("frame")
        self.verticalFrame = QtWidgets.QFrame(self.frame)
        self.verticalFrame.setGeometry(QtCore.QRect(0, 360, 331, 451))
        self.verticalFrame.setStyleSheet("background-color: rgb(20, 128, 140);\n"
"background-color: rgb(2, 81, 89);\n"
"")
        self.verticalFrame.setObjectName("verticalFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalFrame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.verticalFrame)
        self.label_2.setStyleSheet("background-color: rgb(46, 166, 132);\n"
"font: italic 14pt \"Sitka\";\n"
"color: rgb(242, 242, 242);\n"
"\n"
"border: 3px solid #14808c;")
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.verticalFrame)
        self.label_3.setStyleSheet("background-color: rgb(46, 166, 132);\n"
"font: italic 14pt \"Sitka\";\n"
"color: rgb(242, 242, 242);\n"
"\n"
"border: 3px solid #14808c;")
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_5 = QtWidgets.QLabel(self.verticalFrame)
        self.label_5.setStyleSheet("background-color: rgb(46, 166, 132);\n"
"font: italic 14pt \"Sitka\";\n"
"color: rgb(242, 242, 242);\n"
"\n"
"border: 3px solid #14808c;")
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.verticalFrame)
        self.label_6.setStyleSheet("background-color: rgb(46, 166, 132);\n"
"font: italic 14pt \"Sitka\";\n"
"color: rgb(242, 242, 242);\n"
"\n"
"border: 3px solid #14808c;")
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.label_4 = QtWidgets.QLabel(self.verticalFrame)
        self.label_4.setStyleSheet("background-color: rgb(46, 166, 132);\n"
"font: italic 14pt \"Sitka\";\n"
"color: rgb(242, 242, 242);\n"
"\n"
"border: 3px solid #14808c;")
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label = QtWidgets.QLabel(self.verticalFrame)
        self.label.setStyleSheet("background-color: rgb(46, 166, 132);\n"
"font: italic 10pt \"Sitka\";\n"
"color: rgb(242, 242, 242);\n"
"\n"
"border: 3px solid #14808c;")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_7 = QtWidgets.QLabel(self.verticalFrame)
        self.label_7.setStyleSheet("background-color: rgb(46, 166, 132);\n"
"font: italic 14pt \"Sitka\";\n"
"color: rgb(242, 242, 242);\n"
"\n"
"border: 3px solid #14808c;")
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(self.verticalFrame)
        self.label_8.setStyleSheet("background-color: rgb(46, 166, 132);\n"
"font: italic 14pt \"Sitka\";\n"
"color: rgb(242, 242, 242);\n"
"\n"
"border: 3px solid #14808c;")
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.frame_11 = QtWidgets.QFrame(self.frame)
        self.frame_11.setGeometry(QtCore.QRect(10, 10, 311, 351))
        self.frame_11.setStyleSheet("background-color: rgb(20, 128, 140);")
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.label_10 = QtWidgets.QLabel(self.frame_11)
        self.label_10.setGeometry(QtCore.QRect(0, 0, 311, 41))
        self.label_10.setStyleSheet("font: italic 14pt \"Sitka\";\n"
"background-color: rgb(2, 111, 121);\n"
"color: rgb(242, 242, 242);\n"
"border: 3px solid #2ea684;")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.label_14 = QtWidgets.QLabel(self.frame_11)
        self.label_14.setGeometry(QtCore.QRect(0, 40, 311, 311))
        self.label_14.setText("")
        self.label_14.setPixmap(QtGui.QPixmap(".\\mission_planner_flight_data.jpg"))
        self.label_14.setScaledContents(True)
        self.label_14.setObjectName("label_14")
        self.modelt = QtWidgets.QFrame(self.frame_11)
        self.modelt.setGeometry(QtCore.QRect(0, 40, 311, 311))
        self.modelt.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.modelt.setFrameShadow(QtWidgets.QFrame.Raised)
        self.modelt.setObjectName("modelt")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(360, 120, 341, 371))
        self.frame_2.setStyleSheet("background-color: rgb(2, 81, 89);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.frame_13 = QtWidgets.QFrame(self.frame_2)
        self.frame_13.setGeometry(QtCore.QRect(10, 10, 321, 351))
        self.frame_13.setStyleSheet("background-color: rgb(20, 128, 140);")
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.label_11 = QtWidgets.QLabel(self.frame_13)
        self.label_11.setGeometry(QtCore.QRect(0, 0, 321, 41))
        self.label_11.setStyleSheet("font: italic 14pt \"Sitka\";\n"
"color: rgb(242, 242, 242);\n"
"border: 3px solid #2ea684;\n"
"background-color: rgb(2, 111, 121);")
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.map = QtWidgets.QFrame(self.frame_13)
        self.map.setGeometry(QtCore.QRect(-20, -10, 361, 381))
        self.map.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.map.setFrameShadow(QtWidgets.QFrame.Raised)
        self.map.setObjectName("map")
        self.map.raise_()
        self.label_11.raise_()
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(710, 120, 361, 371))
        self.frame_3.setStyleSheet("background-color: rgb(2, 81, 89);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.frame_14 = QtWidgets.QFrame(self.frame_3)
        self.frame_14.setGeometry(QtCore.QRect(10, 10, 341, 351))
        self.frame_14.setStyleSheet("background-color: rgb(20, 128, 140);")
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.label_12 = QtWidgets.QLabel(self.frame_14)
        self.label_12.setGeometry(QtCore.QRect(90, 0, 161, 51))
        self.label_12.setStyleSheet("font: italic 14pt \"Sitka\";\n"
"color: rgb(242, 242, 242);\n"
"border: 3px solid #2ea684;\n"
"background-color: rgb(2, 111, 121);")
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.pushButton = QtWidgets.QPushButton(self.frame_14)
        self.pushButton.setGeometry(QtCore.QRect(0, 0, 93, 51))
        self.pushButton.setStyleSheet("border: 3px solid #2ea684;\n"
"font: italic 10pt \"Sitka\";\n"
"color: rgb(242, 242, 242);\n"
"background-color: rgb(2, 111, 121);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_14)
        self.pushButton_2.setGeometry(QtCore.QRect(250, 0, 93, 51))
        self.pushButton_2.setStyleSheet("border: 3px solid #2ea684;\n"
"font: italic 10pt \"Sitka\";\n"
"color: rgb(242, 242, 242);\n"
"background-color: rgb(2, 111, 121);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.frame_14)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 50, 341, 301))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.camera = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.camera.setContentsMargins(0, 0, 0, 0)
        self.camera.setObjectName("camera")
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setGeometry(QtCore.QRect(360, 500, 341, 441))
        self.frame_4.setStyleSheet("background-color: rgb(2, 81, 89);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.frame_12 = QtWidgets.QFrame(self.frame_4)
        self.frame_12.setGeometry(QtCore.QRect(10, 10, 321, 421))
        self.frame_12.setStyleSheet("background-color: rgb(20, 128, 140);")
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.label_9 = QtWidgets.QLabel(self.frame_12)
        self.label_9.setGeometry(QtCore.QRect(0, 0, 321, 41))
        self.label_9.setStyleSheet("font: italic 14pt \"Sitka\";\n"
"color: rgb(242, 242, 242);\n"
"border: 3px solid #2ea684;\n"
"background-color: rgb(2, 111, 121);")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.verticalScrollBar = QtWidgets.QScrollBar(self.frame_12)
        self.verticalScrollBar.setGeometry(QtCore.QRect(310, 0, 16, 401))
        self.verticalScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")
        self.frame_10 = QtWidgets.QFrame(self.centralwidget)
        self.frame_10.setGeometry(QtCore.QRect(20, 10, 1051, 81))
        self.frame_10.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_10.setStyleSheet("background-color: rgb(0, 41, 45);\n"
"")
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.label_13 = QtWidgets.QLabel(self.frame_10)
        self.label_13.setGeometry(QtCore.QRect(540, 10, 501, 61))
        self.label_13.setStyleSheet("font: italic 24pt \"Sitka\";\n"
"background-color: rgb(20, 128, 140);\n"
"color: rgb(242, 242, 242);\n"
"border: 3px solid #2ea684;")
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.label_17 = QtWidgets.QLabel(self.frame_10)
        self.label_17.setGeometry(QtCore.QRect(-10, 0, 151, 81))
        self.label_17.setStyleSheet("image: url(:/icon/Misya Logo4.1.png);")
        self.label_17.setText("")
        self.label_17.setObjectName("label_17")
        self.frame_5 = QtWidgets.QFrame(self.centralwidget)
        self.frame_5.setGeometry(QtCore.QRect(710, 500, 361, 441))
        self.frame_5.setStyleSheet("background-color: rgb(2, 81, 89);")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.frame_15 = QtWidgets.QFrame(self.frame_5)
        self.frame_15.setGeometry(QtCore.QRect(10, 10, 341, 361))
        self.frame_15.setStyleSheet("background-color: rgb(20, 128, 140);")
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.label_15 = QtWidgets.QLabel(self.frame_15)
        self.label_15.setGeometry(QtCore.QRect(0, 0, 341, 51))
        self.label_15.setStyleSheet("font: italic 14pt \"Sitka\";\n"
"color: rgb(242, 242, 242);\n"
"border: 3px solid #2ea684;\n"
"background-color: rgb(2, 111, 121);")
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_15)
        self.pushButton_5.setGeometry(QtCore.QRect(210, 140, 80, 80))
        self.pushButton_5.setStyleSheet("border-radius: 5px;\n"
"color: rgb(242, 242, 242);\n"
"background-color: rgb(2, 81, 89);\n"
"border: 3px solid #f2f2f2;\n"
"font: 26pt \"Sitka\";")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_15)
        self.pushButton_3.setGeometry(QtCore.QRect(130, 60, 80, 80))
        self.pushButton_3.setStyleSheet("border-radius: 5px;\n"
"color: rgb(242, 242, 242);\n"
"background-color: rgb(2, 81, 89);\n"
"border: 3px solid #f2f2f2;\n"
"font: 26pt \"Sitka\";")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_15)
        self.pushButton_4.setGeometry(QtCore.QRect(50, 140, 80, 80))
        self.pushButton_4.setStyleSheet("border-radius: 5px;\n"
"color: rgb(242, 242, 242);\n"
"background-color: rgb(2, 81, 89);\n"
"border: 3px solid #f2f2f2;\n"
"font: 26pt \"Sitka\";")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_15)
        self.pushButton_6.setGeometry(QtCore.QRect(130, 220, 80, 80))
        self.pushButton_6.setStyleSheet("border-radius: 5px;\n"
"color: rgb(242, 242, 242);\n"
"background-color: rgb(2, 81, 89);\n"
"border: 3px solid #f2f2f2;\n"
"font: 26pt \"Sitka\";")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_7.setGeometry(QtCore.QRect(30, 380, 121, 41))
        self.pushButton_7.setStyleSheet("background-color: rgb(20, 128, 140);\n"
"font: italic 14pt \"Sitka\";\n"
"color: rgb(242, 242, 242);")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_8.setGeometry(QtCore.QRect(220, 380, 121, 41))
        self.pushButton_8.setStyleSheet("background-color: rgb(20, 128, 140);\n"
"font: italic 14pt \"Sitka\";\n"
"color: rgb(242, 242, 242);")
        self.pushButton_8.setObjectName("pushButton_8")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(450, 950, 241, 16))
        self.label_16.setObjectName("label_16")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1112, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Hız:"))
        self.label_3.setText(_translate("MainWindow", "İvme:"))
        self.label_5.setText(_translate("MainWindow", "Sıcaklık:"))
        self.label_6.setText(_translate("MainWindow", "Zaman:"))
        self.label_4.setText(_translate("MainWindow", "Batarya Durumu:"))
        self.label.setText(_translate("MainWindow", "Tespit Edilen Yabani Bitki:"))
        self.label_7.setText(_translate("MainWindow", "Nem:"))
        self.label_8.setText(_translate("MainWindow", "Akım:"))
        self.label_10.setText(_translate("MainWindow", "Eğim"))
        self.label_11.setText(_translate("MainWindow", "Harita"))
        self.label_12.setText(_translate("MainWindow", "Kamera"))
        self.pushButton.setText(_translate("MainWindow", "Önceki"))
        self.pushButton_2.setText(_translate("MainWindow", "Sonraki"))
        self.label_9.setText(_translate("MainWindow", "Log"))
        self.label_13.setText(_translate("MainWindow", "MİSYA TARIM"))
        self.label_15.setText(_translate("MainWindow", "Manual Sürüş"))
        self.pushButton_5.setText(_translate("MainWindow", "→"))
        self.pushButton_3.setText(_translate("MainWindow", "↑"))
        self.pushButton_4.setText(_translate("MainWindow", "←"))
        self.pushButton_6.setText(_translate("MainWindow", "↓"))
        self.pushButton_7.setText(_translate("MainWindow", "Start"))
        self.pushButton_8.setText(_translate("MainWindow", "Stop"))
        self.label_16.setText(_translate("MainWindow", "© 2023-2024 Misya Tarım"))

